In [2]:
# THIS IS HOW U IMPORT THE NUMPY IN THE CODE 
import numpy as np 
# HERE THE np IS THE NICK-NAME OF THE NUMPY I HAVE IMPORTING HERE 

In [3]:
# 1. TO HAVE THE NUMPY ARRAY , DECLARE THE SIMPLE LIST LIKE THIS [1,2,3,4,5] and THEN ADD THE NAME OF THE NUMPY (np) WITH
# . DOT OPERATOR AND ARRAY NAME , LIKE THIS
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
# 2. NOW ADDING A STRING IN THE NUMPY ARRAY WE HAVE THE WHOLE ARRAY AS THE STRING , like this
arr2 = np.array([1, 2, 3, 4, "parth"])
print(arr2)
print(type(arr2))

# 3. CREATION OF THE 2-D ARRAY
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(arr_2d, arr_2d.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
['1' '2' '3' '4' 'parth']
<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [4]:
# DIFFERENT TYPES OF FUNCTIONS OF NUMPY- --->👇

# 1. HAVING A 2-D ARRAY WITH ZEROS PRE FILLED IN IT , like this
arrA = np.zeros((3, 3), dtype=int)

#  2. HAVING A 2-D ARRAY WITH ONES PRE FILLED IN IT , like this
arrB = np.ones((3, 3), dtype=int)

# 3. IF U HAVE TO FILL THE WHOLE ANY DIMENSION ARRAY WITH SOME PARTICULAR VALUE , THEN DO IT LIKE THIS
arrC = np.full((4, 4), (2**2))
# 2**2 means 2^2

# 4. IF U HAVE TO MAKE AN IDENTITY MATRIX , THEN DO IT LIKE THIS
arrD = np.eye(4, dtype=int)

# 5. RANGE() USING IN NUMPY ARRAY 
arrE = np.arange(0,10,2)

# 6 LINESPACE() USING IN NUMPY ARRAY 
arrF = np.linspace(1,100,7)
print(arrF)

[  1.   17.5  34.   50.5  67.   83.5 100. ]


In [5]:
# DIFFERENT TYPES OF PROPERTIES OF NUMPY ARRAY 👇
arrA = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])

# 1. TO PRINT THE DIMENSION OF THE ARRAY , (M * N), WHERE M IS THE ROWS AND N IS THE COLOUMNS
# print(arrA.shape)

# 2. TO PRINT THE NUMBER OF ELEMENTS PRESENT IN THE ARRAY
# print(arrA.size)

# 3. TO PRINT THE DATA-TYPES OF THE ELEMENTS PRESENT IN THE ARRAY
# print(arrA.dtype)

# 4. TO PRINT THE DIMENSION OF THE ARRAY
# print(arrA.ndim)

# 5. TO CHANGE THE DATA_TYPE OF THE ALREADY PRESENT ARRAY , TYPE CASTING , THEN WE DO IT LIKE THIS 
float_arr = arrA.astype(np.float64)
print(float_arr , float_arr.dtype)

[[1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]] float64


In [18]:
# OPERATIONS ON NUMPY ARRAY 👇
arr = np.array([[1, 2, 3], [4, 5, 6]])
# print(arr , arr.shape)

# 1. TO RESHAPE 👇
any_variable_name = arr.reshape((3, 2))
# print("NOW U WILL SEE THE NEW SHAPED ARRAY")
# print(any_variable_name , any_variable_name.shape)

# 2. FLATTENING OF THE ARRAY
flattened = arr.flatten()
# print("NOW U WILLS SEE THE CONVERSION OF ARRAY FROM N DIMENSIONS TO 1 DIMENSIONS ")
# print(flattened , flattened.shape)

# 3. INDEXING IN THE ARRAY
arrA = np.array([[1, 2, 3], [4, 5, 6]])
# print(arrA[0][1]) # --> 2 , row = 0 , column = 1
# print(arrA[1][1]) # --> 5 , row = 1 and column = 1

# 4. BOOLEAN INDEXING
arrB = np.array([1, 2, 3, 4, 5, 6])
# print(arrB[arrB > 2])
# print(arrB[arrB % 2 == 0])

# 5. SLICING 
arrC = np.array([1, 2, 3, 4, 5, 6])
# [START , END , STEP]
# print(arrC[1:4])